name: CD

on:
  push:
    branches:
      - 'current'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy_environment
    steps:
      - name: Run deploy on staging server
        env:
          AUTHKEY: ${{ secrets.XSEAUTH }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL_STAGING }}
        run: |
          curl -X POST -H "X-SE-Auth: $AUTHKEY" $WEBHOOK_URL
