name: CD to prod

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy_environment
    steps:
      - name: Run deploy on production server
        env:
          AUTHKEY: ${{ secrets.XSEAUTH }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          curl -X POST -H "X-SE-Auth: $AUTHKEY" $WEBHOOK_URL
