name: Basic checks

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
            python-version: [ '3.12', '3.11' ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            python-version: ${{ matrix.python-version }}
            cache: 'pip' # caching pip dependencies
      - name: Install fresh pip
        run: python -m pip install -U pip
      - name: Install requirements # Check problems with dependencies
        run: python -m pip install -r requirements.txt
      - name: Init databases # Check basic scenario -- database initialization
        working-directory: src
        run: python flask_se.py init
